---
# tasks file for install
- name: install packages
  yum:
    name:
      - qemu-kvm 
      - qemu-img
      - virt-install 
      - libvirt 
      - libvirt-python 
      - virt-manager 
      - libvirt-client
      - virt-install
      - iptables-services
    state: latest

- name: start libvirtd
  service:
    name: libvirtd
    state: started
    enabled: true

- name: create the interface configuration files
  template:
    src: interface.yml
    dest: /etc/sysconfig/network-scripts/ifcfg-{{item.interface}}
  vars:
    interface_name: "{{item.interface}}"
    bridge_name: "{{item.bridge}}"
  with_items: 
    - "{{lab_bridge}}"
    - "{{provisioning_bridge}}"
    - "{{external_bridge}}"
  notify:
    - restart network

- name: create the bridge configuration files
  template:
    src: bridge.yml
    dest: /etc/sysconfig/network-scripts/ifcfg-{{item.bridge}}
  vars:
    bridge_name: "{{item.bridge}}"
  with_items: 
    - "{{lab_bridge}}"
    - "{{provisioning_bridge}}"
    - "{{external_bridge}}"
  notify:
    - restart network

- name: Disable firewalld if running
  service:
    name: firewalld
    state: stopped
    enabled: false
  ignore_errors: true

- name: Start iptables
  service:
    name: iptables
    state: started
    enabled: true

- name: iptables rules for bridges
  shell:
    cmd: iptables -I FORWARD -m physdev --physdev-is-bridged -j ACCEPT
  notify:
    - save iptables
    - restart iptables
- name: Disable networkmanager
  service:
    name: NetworkManager
    state: stopped
    enabled: no

- name: Ansible no strict host checking
  ini_file:
    path: /etc/ansible/asnbile.cfg
    section: defaults
    option: host_key_checking
    value: False
