---
# handlers file for install
- name: restart network
  service:
    name: network
    state: restarted

- name: save iptables
  shell:
    cmd:
      iptables-save

- name: restart iptables
  service:
    name: iptables
    state: restarted
